name: flutter_side_menu
description: Flutter's full customizable side menu has been used as a directory for Related Pages, Navigation Items, and more.
version: 0.0.4
homepage: https://github.com/resfandiari/flutter_side_menu

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^4.2.0
  auto_size_text: ^3.0.0
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

